"""

Script to calculate Protein weight in Da

"""

Weight_map = {'A': 71.03711,
              'C': 103.00919,
              'D': 115.02694,
              'E': 129.04259,
              'F': 147.06841,
              'G': 57.02146,
              'H': 137.05891,
              'I': 113.08406,
              'K': 128.09496,
              'L': 113.08406,
              'M': 131.04049,
              'N': 114.04293,
              'P': 97.05276,
              'Q': 128.05858,
              'R': 156.10111,
              'S': 87.03203,
              'T': 101.04768,
              'V': 99.06841,
              'W': 186.07931,
              'Y': 163.06333}

Mass_water = 18.01056

def protein_weight(protein_string):
    """

    :param protein_string: String of amino acids
    :return: Mass of protein
    """
    codon = []
    length = len(protein_string)
    mass = 0
    total_water = (length - 1) * Mass_water

    for i in range(0, length):
        codon.append(protein_string[i])
    print(codon)

    for element in codon:
        mass += (Weight_map[(element)])

    print(mass)
    mass = round(mass, 9)
    print(mass)
    return mass

protein_weight('TADH')
protein_weight('SKADYEK')
protein_weight('MNKKWSVNMFWRKVSQMYVWAFWLVENLSYGPDQMPTSESIRQMEVACKATWNEWWNCNKPDSWWSCMQRCICLFWFSFQASQWTNSKRRVHWHWWMDKKPVWTYWPRCEYCKYGICATYGIYFERDFWQYWIPGWDNCFKSRAIFCSNSKWTQNLHRNFWDDCQQPNMMSNCNTCHFEMAPVKDVDPPWVPWVPMTRLVEVNEFVIYIQEVHDPDHPRFNVDSEGCKNAINWDHNPEFMVGVVPTTGINIEGYGQDQVHVVYTMFVVHDTVEDMKKQPAVWLKEHIGHLCAIILLPLAIDTQDTRWMWIDCYNSNRIMPNWMMYWSCWVMAAMGVVHAPFNQERGSAISQKKSIHPLQGGFFMFGDGCGYHDGRAQESNTSDWGMDPWSFMWFNCDHPAYWLSVSWGAFAQGAQLSMFINYACCWASTARILTHKDQWWAVTFNFMQSQRWEEHWDSLPTLSSFAKIYWKSPMHWDPKLGSWWQWDKDDCFNVYCCVLAFYKNRLRQLFLYPTMAIQSRAKMDASHVPGTSVEMFSWCMVGVLMYKGMHWVLMSMQMCYWWKVERFMCTAQPVERFRSEAMRVKEEAVNPCWSNQFPFHICFPFPRHMNIWCMMQNSFVARNQKSIFTPMLHTKCGMNAMRERVCYSECGLTYQESGDDWVMYWYNASKPCMKEWGCTHSRHESDMWGQPRYDHFWIGDWFTAIDVGPEIMTSHHLYCEAVAQWKQAHCFQGTDEEALPYLEGSMLDHKDCTQMTNVSSTISMGFLCHNLSTLPNLNWEIDWMEDPYVLQVLARGNAAAIQCCNEPFTRDLFHDGHTCSSMSETKPAIGNAPTIWPAHFWKKVVTHCWIRLLVIGETT')