"""

a script to find the starting positions of a substring sequence in a longer sequence
    rosalind SUBS
"""

def motif(strand, sub_string):
    """

    :param strand: DNA strand
    :param sub_string: DNA sub-string
    :return: A list of the starting positions of the sub-string motif in the larger sequence
    """
    strand_length = len(strand)
    sub_string_length = len(sub_string)
    diff = strand_length - sub_string_length
    beginning = []
    for i in range(0, diff):
        if strand[i:(i + sub_string_length)] == sub_string:
            print((i + 1))
            beginning.append((i + 1))
    print(beginning)

motif('GATATATGCATATACTT', 'ATAT')

motif('GATTCATATATGCGCA', 'GA')

motif('TGCTGCGTAAGTGCTGCGTAGCTGCGTATATAGTCTGCGTACTACGCTGCGTACCCTGCGTAACTGCGTACCTGCGTACTGCGTACTGCGTATTATACCTGCGTACTGCGTAGACTGCGTAGCCTGCGTAAGCAGCCCTATGTCTGCGTATGAACTGCGTAACGAGTGGCACTGCGTATTACTCAGCTGCGTATACTGCGTAGTCTGCGTACTGCGTACAGGACCTGCGTATACCTGCGTATCTGCGTACTGCGTAAACCTGCGTACTTGACTGCGTACTGCGTATACTGCGTAGCGCTGCGTATTATCTGCGTACTGCGTAGCTGCGTATGCTGCGTACTGCGTAGGCTGCGTATCTGCGTACTGCGTACTGCGTAACTGCGTAATCTGCGTAACTGCGTAGCCTTCCTGCGTAGCCTGCGTAAAACAGCAAACTGCGTACTGCGTACTGAGGGTCTGCGTAGAACTGCGTATTCACGACTGCGTACCTGCGTACATCCTGCGTAGACCTGCGTATGTTGGCTGCGTAGACTGCGTAGCTGCGTATCTGCGTAAACCTGCGTACTGCGTAAACCTGCGTAGCCTGCGTAGATCTGCTGCGTACTGCGTAAGCTGCGTAACTGCGTACGCTGCGTACCTATAGTCTGCGTATGACTGCGTAGCTGCGTACTGCGTACTGCGTACATAAGGAGCTCTGCGTAACCTGCGTACTGCGTAACTGCGTACTGCGTAAGGTACTACGAACTGCGTAGCTGCGTAGGAGGTGATACCCCTGCGTACTGCGTACTGCGTACTGCGTACTGCGTATAGCTGCGTATGCTGATAGACCCTTGAACGTGCCTGCGTAATCCCTCTGCGTACTGCGTACATTT', 'CTGCGTACT')