"""

Script to calculate hamming distance
    rosalind HAMM
"""


def ham(s, t):
    """

    :param s: DNA string
    :param t: DNA string
    :return: hamming distance
    """
    # dont need to mutate string to opposite bases
    comp = []
    ham_dist = 0
    str_comp = ""
    l = len(s)
    # for letter in s:
    #     if letter == 'G':
    #         comp.append('C')
    #     elif letter == 'C':
    #         comp.append('G')
    #     elif letter == 'A':
    #         comp.append('T')
    #     elif letter == 'T':
    #         comp.append('A')
    #     else:
    #         raise ValueError
    # print(comp)
    # for item in comp:
    #     str_comp += item
    # print(str_comp)
    for i in range(l):
        if s[i] != t[i]:
            ham_dist += 1
    print(ham_dist)


ham("TGACCCGTTATGCTCGAGTTCGGTCAGAGCGTCATTGCGAGTAGTCGTTTGCTTTCTCAAACTCC", "GAGCGATTAAGCGTGACAGCCCCAGGGAACCCACAAAACGTGATCGCAGTCCATCCGATCATACA")

ham("GAGCCTACTAACGGGAT", "CATCGTAATGACGGCCT")

ham("GATTACA", "GACTATA")

ham("CGGGTGTCGTGCCTCATCACATAAAGATATAGGACCTCCTGGCAAGGTTTTTCTTTGGAGCTCTTGGCATTCGAAACTGGATAAACACCCACATGTATGATCTGCTTGCAAGTGCAGGTCGAGACGTCCCCGCGCCATGCGAGGGTCCATCGCTGTTAGCTAAGCATGTACTCGACGTCGTCTCGGTTCGTAGATAGCCAATGTCCTGGAGCATGCCGAGGAATGGTGTGGGGCTGTACGCGTACAAGAAGTAGAAAGAGGGGCCAATCCCATTGTAAAACGATTCAACCGTAGCGGTCGGCCGTAGTCGTCCTAGGAACCCGTAGGAGGATTAAAGTCATCACATGTGTCAACGGATTAGAGGGATAGTGCATAGTGCGACGTGCCTGAACGCCCAACTAAGGCTAAGCCGAGGTCTTAGTCCATTTGTTAGCACCGATTTCTGCTTGTTTGCGTGCATAAAAGCAACGTATGGACGAGCACATCGGTGACACGAAAGTTACACGACGGATGCGTCTTTGTATACGATCATCTCGTTTTCCAAACGAAGACTACGACAGGCATCCAGACACGAGCGACTGAAATTCTTGCAGTGGCAGATATTAAATGACTCATGGGGGAAGGTATGACGCTCAATCAGCCTTTGACTGAGGTTTGGTTAGCGAGGATAATGCTAAGAGCATTGAGGTCGGTTGCGCATTATCCCCGAGGAATGTAACCCGAATATCCATCCTACGTGACGCCTGTTATGCCCCTAACGACTGAATCTCCCACGGACTATCTAAAGTTTATACAACCGTGCTCTTGCCTGGCCTGGAACCGAGAAACCTACCTGACGCTTCGAGACGCTTCCGCTAAATCTTGCAAGAGGGGCTTGGCTCTTTTTTGTGAGTCAGATGTGACCACCGCCCATTACGTTGCTACGTGCAT", "GTTTTGTCGTTACTCAGCCCAGAATGGCACACCACCTTCCGCTATGGTCTTCCATAGGACATATAGGAATTAGAATTTGGAGAAAGCGCAACATGGTTAATGGGGGTGAAATTCTAGTATGTCAGGATTAATGTACATGTCCGATTCAGGACCTCTCAACGACGAACGTACGTGACGTCATCTTGGAACGGTGGTAGCGCATCGCAAAGAGACTACGGAACAATCCTGTCGTCCTGCACAGTTAAGACCAGACGATTGAGGTACGCATCCCCGCCGGTACCTATACCATCGTAGGAGTCGGTCGTATTGGTCCTTCGACCGCTTCGGAAGATCACCTTCGTCTATTACCACATGCGGTTCGCGCAAGTGTATGTAAGGCCGCCATCCAGAACTGATAACTATCCGTGATCCTAGGGAACCGTTAATGCCGAAGGCCTGATAGTGGTTTCGTTCCGAGTATTCAGGGAAATTACGGACGAGCATAGCACCTACGTGGGAGTAACGGGTCTGTTCATTCTAAGTGTCCGATCTTGCCATTTAACATACGGTGAGCCAAACAGTCGTGCGAGAGCGCGCAACTGTAATGGTATCCGGTACAGTATCCAGATACCTCCGGCTAGAAGAGGTGACGTACATATAGTAGCGTGCTGACAGTATCGAATTGAGTATAGTATTTCAACTATTGTAGTCGTCATCGCACTATTCCGGACGCTAGTATCCCGAGAAAGCATCGATGCGGAAGGTTGTTGTATTAGGGACTGCGTTATCGGAAGCCTACTCTTCAAACTATGACGTCCCCAGCTCCTGCCTGGACTGGACGCGCGTACGTTACTGTCCTGTAAGCCTTGAGTCCGGCTCTTCTTGCGATTGATGCTTGGTGCTTATTGAATCGAGGTACCGGGACCGATGGACGGCTTGTCCTGCGCGAAA")